version: '3.5'

services:
    html2pdf:
        image: appvantage/html2pdf-service:1.4.1

    mail:
        image: mailhog/mailhog:v1.0.0

    redis:
        image: redis:6.2.6
        command: redis-server --appendonly yes
        volumes:
            - redis:/data

    minio:
        image: minio/minio:RELEASE.2021-07-08T01-15-01Z
        environment:
            MINIO_ROOT_USER: 'AKIAIOSFODNN7EXAMPLE'
            MINIO_ROOT_PASSWORD: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
        command: ['server', '/data', '--console-address', ':9001']
        volumes:
            - minio:/data

    mongo:
        container_name: iso-kit-mongo
        # can be replace by ghcr.io/appvantageasia/mongo-entreprise:X.X.X
        # changes to be done in override file
        image: mongo:5.0.6
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo:/data/db
        networks:
            - mongo-compose-network

    mongo-express:
        image: mongo-express:latest
        container_name: iso-kit-mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: iso-kit-mongo
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: password

        ports:
            - 8081:8081
        links:
            - mongo
        depends_on:
            - mongo
        networks:
            - mongo-compose-network

volumes:
    mongo:
    redis:
    minio:
networks:
    mongo-compose-network:
        driver: bridge
